services:
  - type: web
    name: nazava-analytics
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24.10.0
